name: 'Sync release'
description: 'Synchronizes the release branch with main after a rebase-merge. | Copyright 2024 MusTalK (https://github.com/mustalk)'

inputs:
  release-branch:
    description: 'The release branch to sync.'
    required: true
    default: 'release'
  main-branch:
    description: 'The main branch to sync with.'
    required: true
    default: 'main'
  remote-name:
    description: 'The remote name to use for fetch/push.'
    required: true
    default: 'origin'
  gpg-key:
    description: 'The GPG private key for signing commits.'
    required: true
  gpg-passphrase:
    description: 'The passphrase for GPG signing.'
    required: true

runs:
  using: 'composite'
  steps:
    # Initialize default status to skipped, so we can check if the script has been executed successfully or not in the workflow.
    - name: Initialize default action status
      run: |
        echo "SYNC_RELEASE_STATUS=skipped" >>"$GITHUB_ENV"
        echo "SYNC_RELEASE_MESSAGE='Synchronization step was skipped.'" >>"$GITHUB_ENV"
      shell: bash

    # Grants execute permissions to all shell scripts.
    - name: Grant Execute Permission
      run: |
        git config --global core.filemode false
        chmod +x .github/scripts/utils/helpers/grant-exec-perms.sh
        .github/scripts/utils/helpers/grant-exec-perms.sh
      shell: bash

    # Runs the GPG setup script with the GPG private key from inputs.
    - name: Setup GPG
      run: .github/scripts/gpg-signing/setup.sh
      shell: bash
      env:
        BOT_GPG_PKEY: ${{ inputs.gpg-key }}
        GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}

    # Synchronizes the release branch with main after a rebase-merge.
    - name: Synchronize release branch
      if: success()
      run: .github/scripts/release/auto/sync-release.sh
      shell: bash
      env:
        RELEASE_BRANCH: ${{ inputs.release-branch }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        REMOTE_NAME: ${{ inputs.remote-name }}

    # Runs the GPG cleanup script to remove the GPG agent and key.
    - name: Cleanup GPG
      if: always()
      run: .github/scripts/gpg-signing/cleanup.sh
      shell: bash
