build:
    maxIssues: 3
    excludeCorrectable: true
    weights:
    # Uncomment and adjust weights for specific rules as needed
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
    validation: true
    warningsAsErrors: true
    checkExhaustiveness: false
    # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
    excludes: ''

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'
        - 'ComplexityReport'
        - 'NotificationReport'
        - 'FindingsReport'
        - 'FileBasedFindingsReport'
    #  - 'LiteFindingsReport'

style:
    MaxLineLength:
        active: true
        maxLineLength: 150
        excludePackageStatements: true
        excludeImportStatements: true
        excludeCommentStatements: false
        excludeRawStrings: true

complexity:
    active: true
    CognitiveComplexMethod:
        active: false
        threshold: 15
    ComplexInterface:
        active: false
        threshold: 10
        includeStaticDeclarations: false
        includePrivateDeclarations: false
        ignoreOverloaded: false
    LargeClass:
        active: true
        threshold: 600
    LongMethod:
        active: true
        threshold: 60
    LongParameterList:
        active: true
        functionThreshold: 6
        constructorThreshold: 7
        ignoreDefaultParameters: false
        ignoreDataClasses: true
        ignoreAnnotatedParameter: [ ]
    TooManyFunctions:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
        thresholdInFiles: 11
        thresholdInClasses: 11
        thresholdInInterfaces: 11
        thresholdInObjects: 11
        thresholdInEnums: 11
        ignoreDeprecated: false
        ignorePrivate: false
        ignoreOverridden: false
        ignoreAnnotatedFunctions: [ ]
        ignoreAnnotated: [ 'dagger.Module' ] # Ignore classes annotated with @Module
